name: ingest-data
on:
  schedule:
    - cron: '*/12 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \ 
          --url https://heatsat.vercel.app/api/ingest-data \ 
          --u ${{ secrets.BASIC_USER }}:${{ secrets.BASIC_PASS }} \ 
          --fail

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
